# .pre-commit-config.yaml
repos:
  # Hooks genéricos para manutenção de arquivos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Remove espaços no final das linhas
      - id: end-of-file-fixer # Garante uma linha em branco no final do arquivo
      - id: check-yaml # Valida arquivos YAML
      - id: check-toml # Valida arquivos TOML
      - id: check-json # Valida arquivos JSON
      - id: check-case-conflict # Evita nomes de arquivos com conflito
