# .pre-commit-config.yaml
repos:
  # Hooks genéricos para manutenção de arquivos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Remove espaços no final das linhas
      - id: end-of-file-fixer # Garante uma linha em branco no final do arquivo
      - id: check-yaml # Valida arquivos YAML
      - id: check-toml # Valida arquivos TOML

  # Hook para o Ruff (linter e formatador)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Tenta corrigir erros
      - id: ruff-format

  # Hook para o Mypy (checagem de tipos)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          ['fastapi', 'sqlalchemy', 'pydantic', 'pydantic-settings']
