# .github/workflows/ci.yml

name: CI - Testes Python com Poetry e Taskipy

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # [GEMINI] CORREÇÃO APLICADA AQUI:
      # Adicionamos '+aiosqlite' para dizer ao SQLAlchemy para usar o driver async.
      DATABASE_URL: 'sqlite+aiosqlite:///./test.db'
      SECRET_KEY: 'super-secret-key-for-testing-purposes-only'
      ALGORITHM: 'HS256'
      ACCESS_TOKEN_EXPIRE_DAYS: '7'

    steps:
      # ... (o resto do arquivo continua igual) ...
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: pipx install poetry

      - name: Configurar cache do Poetry
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Instalar dependências
        run: |
          poetry install --no-interaction --no-root

      - name: Rodar os testes com Pytest
        run: |
          poetry run task test
