# .github/workflows/ci.yml

name: CI - Testes Python com Poetry e Taskipy

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    # [GEMINI] NOVA SEÇÃO ADICIONADA AQUI
    # Define variáveis de ambiente para este job específico.
    env:
      DATABASE_URL: 'sqlite:///./test.db' # Usando um banco SQLite em arquivo para os testes

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: |
          pipx install poetry

      - name: Configurar cache do Poetry
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Instalar dependências
        run: |
          poetry install --no-interaction --no-root

      - name: Rodar os testes com Pytest
        run: |
          poetry run task test
